# .streamlit/secrets.toml

# Replace "YOUR_ACTUAL_GEMINI_API_KEY_GOES_HERE" with your real Gemini API key
gemini_api_key = "YOUR_GEMINI_API"  

# If you want to store your Gmail App Password securely, you can add it here too:
# gmail_app_password = "YOUR_GMAIL_APP_PASSWORD_GOES_HERE"
